More user-friendly deploy

diff --git a/warcannon b/warcannon
--- a/warcannon
+++ b/warcannon
@@ -37,7 +37,35 @@ deploy () {
 		exit 1
 	fi
 
-	echo "[*] Preparing to deploy the warcannon"
+	POPULATEATHENA=0
+	[[ ! -d .terraform ]] && POPULATEATHENA=1
+
+	echo "[*] Preparing to deploy the WARCannon"
+
+	BUCKET=$(jq -r '.backendBucket' settings.json 2> /dev/null)
+
+	if [[ "$BUCKET" == "" ]]; then
+		echo "No backend bucket is specified in settings.json. This is best practice and required for WARCannon."
+		echo "If you specify a bucket that doesn't exist, WARCannon will create it for you. How easy is that?"
+		echo "Update settings.json and try again."
+		echo ""
+		exit 1
+	fi
+
+	EXISTS=$(aws --profile $(jq -r '.awsProfile' settings.json) s3api get-bucket-location --bucket $BUCKET)
+	if [[ $? -ne 0 ]]; then
+		aws --profile $(jq -r '.awsProfile' settings.json) s3api create-bucket --bucket $BUCKET --create-bucket-configuration LocationConstraint=us-east-1
+
+		if [[ $? -ne 0 ]]; then
+			echo "Error creating backendBucket. Fix that^ error then try again."
+			exit 1
+		fi
+	else
+		if [[ $( curl -s --head $BUCKET.s3.amazonaws.com | grep us-east-1 | wc -l ) -eq 0 ]]; then
+			echo "The backendBucket you specified doesn't reside in us-east-1."
+			exit 1
+		fi
+	fi
 
 	if [[ ! -f regions.json ]]; then
 		echo "[*] Getting availabilityzones from AWS"
@@ -68,11 +96,21 @@ deploy () {
 	jsonnet -m . terraform.jsonnet
 
 	if [[ $? -ne 0 ]]; then
-		"[!] Jsonnet failed. Unable to proceed."
+		echo "[!] Jsonnet failed. Unable to proceed."
+		exit 1
 	fi
 
 	[[ ! -d .terraform ]] && $TERBIN init
 	terraform apply -auto-approve
+
+	if [[ $? -ne 0 ]]; then
+		echo "[!] Terraform failed. Unable to proceed."
+		exit 1
+	fi
+
+	if [[ "$POPULATEATHENA" == "1" ]]; then
+		./populate_athena.sh
+	fi
 }
 
 clearResults () {
@@ -156,54 +194,74 @@ fire () {
 
 showBanner () {
 
-	echo "                                                                                                                                                     "
-	echo "     ((((((  /((((   ((((((  ((((((/     ((((((((((*     /(((((((((      @@@@@@     %@@@@@/  &@@@@@ @@@@@@   @@@@@/    @@@@@@@@@*    @@@@@@   @@@@@  "
-	echo "     ((((((  ((((((  (((((  ((((((((     ((((((((((((  (((((((((((*     @@@@@@@&    %@@@@@@% &@@@@@ @@@@@@@  @@@@@/ &@@@@@@@@@@@@@@  @@@@@@@  @@@@@  "
-	echo "      (((((/#(((((( (((((( *(((((((((    (((((/ (((((*((((((           @@@@@@@@@(   %@@@@@@@@&@@@@@ @@@@@@@@*@@@@@/@@@@@@     @@%/****(#%%(***&@@@@  "
-	echo "       ((((((((((((((((((  ((((( (((((   (((((((((((  ((((((          @@@@@ @@@@@*  %@@@@@@@@@@@@@@ @@@@@%@@@@@@@@/@#/****(##(%%%#/********##*@@@@@  "
-	echo "       ((((((((  (((((((/ (((((((((((((  (((((((((((  /(((((((((((   @@@#***(###/% ####**( @@@@@@@# ***/*****/######%%%(***********#(***(& #@@@@@@@  "
-	echo "        ((((((/  #(((((# (((((*   (((((# (((((/ ((((((  ((((((((****###(/########/%/#####%**((****/#*#/#*%*##*************(%***/@%   @@@@@  /@@@@@@  "
-	echo "                                                         **/#(******//((#########**/######/**//***  *# #*********/#***                               "
-	echo "                                                  */#(*(****** ((/*%(****## *###*##**#####%*#(***(#/**#*#*****                   *                   "
-	echo "                                                *#* **********#**#((*%*##( **/##/*#/(*#####%**###****(****                     #                     "
-	echo "                                              **/%*/**/******#**/##%(#/** *#**/##*##***####%/********(##/                    #*                      "
-	echo "                                          */%((*/*(*#*******%%%%*#((#*%** *****/##*##**/####%******%( ###*##           /###(                         "
-	echo "                                         *#(**(#(**(%%%%(*****%%*#*%(*%%#%%%%(**/#/**#**#(####%******/###/*#*###   #*# *             /               "
-	echo "                                      *  %%%%#* * * ####(%#*#%*(*/##**%%%%%%%%#***####/**#*###############*  #/# *# #(          (#                   "
-	echo "                              (/    #  **##*######/####*%/****#*%%%%#***(((((((***/####***#*** ((####*###/(*****#/(###        //                     "
-	echo "                           #/     #* *#*###/#####**####(%***/%%*%%%%%#**/%%%%%%**(*(####********/(###((//(#*   #*##*##/###                           "
-	echo "                         ((      #/ **#*##*(###(*#/###/%%*#/((/*#%%%##*%*(*###******(/######/* /(#((/*******#####*#*   *###(##/                      "
-	echo "                /#      (#*    *###  %*### */(****####*%%* *#%%**%%%#(*%#******#***#####/#** **#*##########*  **(%%%%* #*** (*                       "
-	echo "             #/      *###*### (#/###*%*###******/*####*%%****#%****%%%/%%**** *%******(/**********(##%%%(/**#%#**(%%%(**    *#*       *              "
-	echo "            #/        #(#####*###  *#%*###(##(########/%(*(***%*******((%**(((*%***#/********#((****/(%#(*******#/****(%##* *#*/ *###*       /       "
-	echo "           ( /   (  **#( ####    //*%/################/%(*********************************************(********#*%***%%%%(#*#*  (#((     ###*        "
-	echo "         ##     ####   ##   ###(*/ *%*##*******/%%/* ** * *********************/%/***//##########***%%(##** ***#*%***%/%%##*/#** #(   /#/            "
-	echo "         (     ### *#((   ##    **/########(/*%%#***(#**%%%%%%*****%*#**(***/#%%(%%%%%#(///*****%%%%%%%%##%%#(***%***(*%%%#/***#*## ##(#*   //       "
-	echo "           #   (#( #(     #  *#**/(#%%%%%%#%#%##   ##(**%%##(%****/(#*#***##%%%%%%%%%%%%%%%%%%/%%%%%%#*%**##**%##/****#%%%## **(#* (((    ((         "
-	echo "          #*###     **/#/***#%%%(**** *****/*%#***(##**%%%%%******#**#**(#%************* */#%%%%%%#*((####*******(%(#** %%##**(%#*####*              "
-	echo "         #(***/#******#*#(*#*****/######((*/*/( **####**#*##%***#  (***##(/**#(((########*#*%%%%#****##%(************%%#*((#****#*   (##(##          "
-	echo "       (#%#%%%%%#%%%%%*#**%/***/%%%####%%%*#*#***#(######/*/**/#/*****#%*(*#*(%%#######(*(*%###*(/****#%%%%%%(%%##******%#/****#(#*   #######        "
-	echo "    *#% (%/********%%*//*%*(*(*/********** /*#***/*(##(##/######*** *#** **************** #/#*#****#**/####%%%%#%%#*#(#****%( */(#*##(  /####((      "
-	echo "   ***%*** *****(**%%*#*#/(##/****** ***********/############/##****#(#%%%%%%#/* *********#*#****#*****##****/##%%%%%%%%##****%(*#*  /##  (*#/#      "
-	echo "     ***#***/#(/***%%**(%%%%%%#%%%%%###*****(***#*****####(***** **/* #%%%%%%%%%%%%%%%%%#******#***#***********  (#%%#/***///***(#*   ##  * ##*      "
-	echo "    *###********##(*%**(##%%%#%%%#####/*****(*************/////****/* */#(#####%#######/**//((**/*%*****************(********##****(*     (##        "
-	echo "   ***#########/(** (/ ***/##*####/*********/****############******# ************/((/*****************(####*(##/****%##/***(#%**(*** #####(          "
-	echo "   /(##(####***********#**********//((((((//##***#############***** ////(#######***********************(######(#*###********#**##**#*    ##/         "
-	echo "  *################(*/*****//#################****####((((((((/****###*** *(#####((#/*** **********(##########**#*/*/%%%%#**/*#** /(*(*/##   /       "
-	echo "  */**/########*/*******%#*(*****##*%(*****###*/**#########(*******%#*%*** **#//%******##****#*#########*####*(****%%#***%(*/##*/****#**####*        "
-	echo "  *(#########/***********%*/#/****##*%***** #(#****###########*****##*%/*****#*/%******#********/###########**#***%%***(#*%*#// */******/#           "
-	echo "   *############( **/*(#**#**%**** #(*%*/***/###******************* #* (  ***#(*%******#******(#(###########*#** #%***#*#*%***(*(/*(/*/**#           "
-	echo "    /###########*/*****(******%*****##*%(/*** ###***************** */#*%*****(#*%******#**/(#//########(/##/*#***%%  *#*#*%** (#**/***#**   #/       "
-	echo "    *(###***(##**(((****(**/****%* **/#/*%*/***/###******************(#*%/****#*%#/****#*****/****////(####*(#***%#* (#(*#***********(***  *         "
-	echo "     *(################* *(#*#************** * /**/***** **************(*/****#//%*****#******#############*/#***%#*#(//*#*#** / **#****/            "
-	echo "       *##(######(#(#***** #****%%%**#*(   */***/********************************/******#** **(####*###(*//* #***%%*/#*(%   /#*(#**#****(#           "
-	echo "        *####((#####/**/##****#*******/ * **/********** **** *  ******************************########(#####*##**(%%%%%/* ( #**(#*(***(*             "
-	echo "          *####(#########*(***** (#*//(# ** ****                           ***** ***********((###############*##%**/(***/* #**/****                  "
-	echo "            */(##****(########(#**#***********                               ****************** ###########****(##%*****/***( **                     "
-	echo "                          * *******                <a c6fc project>           ******        **/*****############*/###*#(##**                         "
-	echo "                                                                                                      ************** *                               "
-	echo
-	echo
+	if [[ $(tput cols) -lt 200 && $(tput cols) -gt 79 ]]; then
+		echo
+		echo "((((((  /((((   ((((((  ((((((/     ((((((((((*     /((((((((("
+		echo "((((((  ((((((  (((((  ((((((((     ((((((((((((  ((((((((((( "
+		echo " (((((/#(((((( (((((( *(((((((((    (((((/ (((((*((((((       "
+		echo "  ((((((((((((((((((  ((((( (((((   (((((((((((  ((((((       "
+		echo "  ((((((((  (((((((/ (((((((((((((  (((((((((((  /((((((((((( "
+		echo "   ((((((/  #(((((# (((((*   (((((# (((((/ ((((((  ((((((((((("
+		echo "         @@@@@@    %@@@@@/  &@@@@@ @@@@@@   @@@@@   @@@@@@@@@@@* @@@@@    @@@@@"
+		echo "        @@@@@@@&   %@@@@@@% &@@@@@ @@@@@@@  @@@@@ &@@@@@@@@@@@@* @@@@@@   @@@@@"
+		echo "       @@@@@@@@@(  %@@@@@@@@&@@@@@ @@@@@@@@*@@@@@ @@@@@     @@@@ @@@@@@@@*@@@@@"
+		echo "      @@@@@ @@@@@* %@@@@@@@@@@@@@@ @@@@@@@@@@@@@@ @@@@@     @@@@ @@@@@@@@@@@@@@"
+		echo "     @@@@@**(@@@@@ %@@@@@  @@@@@@@ @@@@@  @@@@@@@ @@@@@@@@@@@@@/ @@@@@   @@@@@@"
+		echo "   *@@@@@####@@@@@%%@@@@@*  @@@@@@ @@@@@*  @@@@@@   @@@@@@@@@%   @@@@@*   @@@@@"
+		echo
+		echo
+	fi
+
+	if [[ $(tput cols) -ge 200 ]]; then
+		echo "                                                                                                                                                     "
+		echo "     ((((((  /((((   ((((((  ((((((/     ((((((((((*     /(((((((((      @@@@@@     %@@@@@/  &@@@@@ @@@@@@   @@@@@/    @@@@@@@@@*    @@@@@@   @@@@@  "
+		echo "     ((((((  ((((((  (((((  ((((((((     ((((((((((((  (((((((((((*     @@@@@@@&    %@@@@@@% &@@@@@ @@@@@@@  @@@@@/ &@@@@@@@@@@@@@@  @@@@@@@  @@@@@  "
+		echo "      (((((/#(((((( (((((( *(((((((((    (((((/ (((((*((((((           @@@@@@@@@(   %@@@@@@@@&@@@@@ @@@@@@@@*@@@@@/@@@@@@     @@%/****(#%%(***&@@@@  "
+		echo "       ((((((((((((((((((  ((((( (((((   (((((((((((  ((((((          @@@@@ @@@@@*  %@@@@@@@@@@@@@@ @@@@@%@@@@@@@@/@#/****(##(%%%#/********##*@@@@@  "
+		echo "       ((((((((  (((((((/ (((((((((((((  (((((((((((  /(((((((((((   @@@#***(###/% ####**( @@@@@@@# ***/*****/######%%%(***********#(***(& #@@@@@@@  "
+		echo "        ((((((/  #(((((# (((((*   (((((# (((((/ ((((((  ((((((((****###(/########/%/#####%**((****/#*#/#*%*##*************(%***/@%   @@@@@  /@@@@@@  "
+		echo "                                                         **/#(******//((#########**/######/**//***  *# #*********/#***                               "
+		echo "                                                  */#(*(****** ((/*%(****## *###*##**#####%*#(***(#/**#*#*****                   *                   "
+		echo "                                                *#* **********#**#((*%*##( **/##/*#/(*#####%**###****(****                     #                     "
+		echo "                                              **/%*/**/******#**/##%(#/** *#**/##*##***####%/********(##/                    #*                      "
+		echo "                                          */%((*/*(*#*******%%%%*#((#*%** *****/##*##**/####%******%( ###*##           /###(                         "
+		echo "                                         *#(**(#(**(%%%%(*****%%*#*%(*%%#%%%%(**/#/**#**#(####%******/###/*#*###   #*# *             /               "
+		echo "                                      *  %%%%#* * * ####(%#*#%*(*/##**%%%%%%%%#***####/**#*###############*  #/# *# #(          (#                   "
+		echo "                              (/    #  **##*######/####*%/****#*%%%%#***(((((((***/####***#*** ((####*###/(*****#/(###        //                     "
+		echo "                           #/     #* *#*###/#####**####(%***/%%*%%%%%#**/%%%%%%**(*(####********/(###((//(#*   #*##*##/###                           "
+		echo "                         ((      #/ **#*##*(###(*#/###/%%*#/((/*#%%%##*%*(*###******(/######/* /(#((/*******#####*#*   *###(##/                      "
+		echo "                /#      (#*    *###  %*### */(****####*%%* *#%%**%%%#(*%#******#***#####/#** **#*##########*  **(%%%%* #*** (*                       "
+		echo "             #/      *###*### (#/###*%*###******/*####*%%****#%****%%%/%%**** *%******(/**********(##%%%(/**#%#**(%%%(**    *#*       *              "
+		echo "            #/        #(#####*###  *#%*###(##(########/%(*(***%*******((%**(((*%***#/********#((****/(%#(*******#/****(%##* *#*/ *###*       /       "
+		echo "           ( /   (  **#( ####    //*%/################/%(*********************************************(********#*%***%%%%(#*#*  (#((     ###*        "
+		echo "         ##     ####   ##   ###(*/ *%*##*******/%%/* ** * *********************/%/***//##########***%%(##** ***#*%***%/%%##*/#** #(   /#/            "
+		echo "         (     ### *#((   ##    **/########(/*%%#***(#**%%%%%%*****%*#**(***/#%%(%%%%%#(///*****%%%%%%%%##%%#(***%***(*%%%#/***#*## ##(#*   //       "
+		echo "           #   (#( #(     #  *#**/(#%%%%%%#%#%##   ##(**%%##(%****/(#*#***##%%%%%%%%%%%%%%%%%%/%%%%%%#*%**##**%##/****#%%%## **(#* (((    ((         "
+		echo "          #*###     **/#/***#%%%(**** *****/*%#***(##**%%%%%******#**#**(#%************* */#%%%%%%#*((####*******(%(#** %%##**(%#*####*              "
+		echo "         #(***/#******#*#(*#*****/######((*/*/( **####**#*##%***#  (***##(/**#(((########*#*%%%%#****##%(************%%#*((#****#*   (##(##          "
+		echo "       (#%#%%%%%#%%%%%*#**%/***/%%%####%%%*#*#***#(######/*/**/#/*****#%*(*#*(%%#######(*(*%###*(/****#%%%%%%(%%##******%#/****#(#*   #######        "
+		echo "    *#% (%/********%%*//*%*(*(*/********** /*#***/*(##(##/######*** *#** **************** #/#*#****#**/####%%%%#%%#*#(#****%( */(#*##(  /####((      "
+		echo "   ***%*** *****(**%%*#*#/(##/****** ***********/############/##****#(#%%%%%%#/* *********#*#****#*****##****/##%%%%%%%%##****%(*#*  /##  (*#/#      "
+		echo "     ***#***/#(/***%%**(%%%%%%#%%%%%###*****(***#*****####(***** **/* #%%%%%%%%%%%%%%%%%#******#***#***********  (#%%#/***///***(#*   ##  * ##*      "
+		echo "    *###********##(*%**(##%%%#%%%#####/*****(*************/////****/* */#(#####%#######/**//((**/*%*****************(********##****(*     (##        "
+		echo "   ***#########/(** (/ ***/##*####/*********/****############******# ************/((/*****************(####*(##/****%##/***(#%**(*** #####(          "
+		echo "   /(##(####***********#**********//((((((//##***#############***** ////(#######***********************(######(#*###********#**##**#*    ##/         "
+		echo "  *################(*/*****//#################****####((((((((/****###*** *(#####((#/*** **********(##########**#*/*/%%%%#**/*#** /(*(*/##   /       "
+		echo "  */**/########*/*******%#*(*****##*%(*****###*/**#########(*******%#*%*** **#//%******##****#*#########*####*(****%%#***%(*/##*/****#**####*        "
+		echo "  *(#########/***********%*/#/****##*%***** #(#****###########*****##*%/*****#*/%******#********/###########**#***%%***(#*%*#// */******/#           "
+		echo "   *############( **/*(#**#**%**** #(*%*/***/###******************* #* (  ***#(*%******#******(#(###########*#** #%***#*#*%***(*(/*(/*/**#           "
+		echo "    /###########*/*****(******%*****##*%(/*** ###***************** */#*%*****(#*%******#**/(#//########(/##/*#***%%  *#*#*%** (#**/***#**   #/       "
+		echo "    *(###***(##**(((****(**/****%* **/#/*%*/***/###******************(#*%/****#*%#/****#*****/****////(####*(#***%#* (#(*#***********(***  *         "
+		echo "     *(################* *(#*#************** * /**/***** **************(*/****#//%*****#******#############*/#***%#*#(//*#*#** / **#****/            "
+		echo "       *##(######(#(#***** #****%%%**#*(   */***/********************************/******#** **(####*###(*//* #***%%*/#*(%   /#*(#**#****(#           "
+		echo "        *####((#####/**/##****#*******/ * **/********** **** *  ******************************########(#####*##**(%%%%%/* ( #**(#*(***(*             "
+		echo "          *####(#########*(***** (#*//(# ** ****                           ***** ***********((###############*##%**/(***/* #**/****                  "
+		echo "            */(##****(########(#**#***********                               ****************** ###########****(##%*****/***( **                     "
+		echo "                          * *******                <a c6fc project>           ******        **/*****############*/###*#(##**                         "
+		echo "                                                                                                      ************** *                               "
+		echo
+		echo
+	fi
 }
 
 showCrawlList () {
